#!/bin/bash

source version
source cross-targets
source tools.sh
# SOURCE_DIR and OUTPUT_DIR must be full path
export SOURCE_DIR="$(pwd)/.src-tarballs"
export OUTPUT_DIR="$(pwd)/output"
export PATCH_DIR="$(pwd)/patch"
export __CMAKE_WRAPPER="$(pwd)/cmake-target-wrapper.sh"

unset EXEC_SUFFIX CROSS_EXEC_SUFFIX
unset SCRIPT_SUFFIX
unset BUILD_HOST
unset MSYS_HOST
__os_name="$(uname -s)"
case "$__os_name" in
    CYGWIN*|MINGW*|MSYS*)
        export BUILD_HOST=Windows
        export EXEC_SUFFIX=".exe"
        export SCRIPT_SUFFIX=".cmd"
        if [[ $__os_name == "CYGWIN"* ]]; then
            export CYGWIN=winsymlinks:native
        else
            export MSYS=winsymlinks:native
            if [ -z "$__MSYS" ]; then
                # Force MinGW64
                export MSYSTEM=MINGW64
                export PATH=/mingw64/bin:/mingw64/sbin:$PATH
                export HOST_CFLAGS="$HOST_CFLAGS -static"
                export HOST_CXXFLAGS="$HOST_CXXFLAGS -static"
                # Add dependent libs for libxml2
                export HOST_LDFLAGS="$HOST_LDFLAGS -static -llzma -lz -liconv -lws2_32"
                export LLVM_CMAKE_FLAGS="$LLVM_CMAKE_FLAGS -DLLVM_BUILD_STATIC=1 -DLIBCLANG_BUILD_STATIC=ON"
                export CONFIGURE_ARGS="$CONFIGURE_ARGS --build=x86_64-w64-mingw32" 
                export BINARYEN_STATIC_BUILD=1
            else
                export MSYS_HOST=1
                export MSYSTEM=MSYS
                export PATH=/usr/bin:/usr/sbin:/bin:/sbin:$PATH
            fi
        fi
        ;;
    Linux*)
        export BUILD_HOST=Linux
        ;;
    Darwin*)
        export BUILD_HOST=Darwin
        export HOST_CFLAGS="$HOST_CFLAGS -mmacosx-version-min=10.9"
        export HOST_CXXFLAGS="$HOST_CXXFLAGS -mmacosx-version-min=10.9 -std=c++11"
        export HOST_LDFLAGS="$HOST_LDFLAGS -mmacosx-version-min=10.9"
        ;;
esac
unset __os_name
export CROSS_HOST=${CROSS_HOST:-${BUILD_HOST}}
if [[ $CROSS_HOST == "Windows" ]]; then
    CROSS_EXEC_SUFFIX=".exe"
fi

# For xcrun, codesign, etc
export PATH="$(pwd)/build-tools:$(pwd)/build-tools/win32-wrapper:$PATH"
