FROM llvm-buildenv-osxcross

ENV CROSS_PREFIX=aarch64-apple-darwin20.4
ENV HOST_CC=$CROSS_PREFIX-cc HOST_CXX=$CROSS_PREFIX-c++ HOST_STRIP=$CROSS_PREFIX-strip \
    HOST_CPP="$CROSS_PREFIX-cc --driver-mode=cpp" \
    HOST_CONFIGURE_ARGS="--host=$CROSS_PREFIX" \
    HOST_LDFLAGS="-L$BUILD_DEPS_ROOT/lib"

ADD build-dep-libs.sh /root
RUN rm -rf ${BUILD_DEPS_ROOT} && SKIP_BUILD_LIBCXX=1 OPENSSL_TARGET=darwin64-arm64-cc ./build-dep-libs.sh
ENV HOST_LDFLAGS="$HOST_LDFLAGS -llzma -lz -liconv"

