FROM tobix/pywine@sha256:07e513ba8b24e9613ebe8910714b1d2cebdf801077e9043f9b30d765a3a588d9

# Replace apt mirros
RUN echo 'Acquire::PDiffs "false";' >> /etc/apt/apt.conf && rm -f /etc/apt/sources.list && rm -f /etc/apt/sources.list.d/*.sources && \
    echo 'deb http://mirrors.ustc.edu.cn/debian/ buster main contrib non-free' > /etc/apt/sources.list && \
    echo 'deb http://mirrors.ustc.edu.cn/debian/ buster-updates main contrib non-free' >> /etc/apt/sources.list && \
    echo 'deb http://mirrors.ustc.edu.cn/debian/ buster-backports main contrib non-free' >> /etc/apt/sources.list && \
    echo 'deb http://mirrors.ustc.edu.cn/debian-security buster/updates main contrib non-free' >> /etc/apt/sources.list
RUN apt update && apt install -y --no-install-recommends \
    gcc g++ git git-lfs wget curl ca-certificates patch unzip xz-utils bzip2 file ninja-build make python3 python3-pip python3-setuptools \
    autoconf automake zlib1g-dev texinfo flex bison help2man gawk libtool libtool-bin libncurses-dev
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip3 install cmake==3.18.4
RUN wine pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /root
ARG CROSS_ARCH=x86_64
ENV CROSS_PREFIX=${CROSS_ARCH}-w64-mingw32 BUILD_DEPS_ROOT=/root/build-deps-root
RUN wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz -O crosstool-ng.tar.xz && \
    mkdir crosstool-ng && cd crosstool-ng && tar xvf ../crosstool-ng.tar.xz --strip 1 && ./configure --prefix=/usr && make install -j$(nproc) && \
    cd /root && rm -rf crosstool-ng*

ADD ${CROSS_PREFIX}-ct-ng.config /root
RUN mkdir ct-${CROSS_PREFIX}-build && cd ct-${CROSS_PREFIX}-build && cp ../${CROSS_PREFIX}-ct-ng.config .config && \
    ct-ng build.$(nproc) && cd .. && rm -rf ct-${CROSS_PREFIX}-build

ENV TOOLCHAIN_ROOT=/root/x-tools/${CROSS_PREFIX}
ENV PATH="${TOOLCHAIN_ROOT}/bin:${BUILD_DEPS_ROOT}/bin:${PATH}" \
    HOST_CC=${CROSS_PREFIX}-gcc HOST_CXX=${CROSS_PREFIX}-g++ HOST_CPP=${CROSS_PREFIX}-cpp \
    HOST_STRIP=${CROSS_PREFIX}-strip HOST_RC=${CROSS_PREFIX}-windres \
    HOST_CPPFLAGS="-I$BUILD_DEPS_ROOT/include" \
    HOST_CFLAGS="-I$BUILD_DEPS_ROOT/include" \
    HOST_CXXFLAGS="-I$BUILD_DEPS_ROOT/include" \
    HOST_LDFLAGS="-L$BUILD_DEPS_ROOT/lib -pthread" \
    HOST_CMAKE_FLAGS="-DCMAKE_FIND_ROOT_PATH=$BUILD_DEPS_ROOT -DCMAKE_SYSTEM_NAME=Windows" \
    HOST_RUNTIME_LIBS="${TOOLCHAIN_ROOT}/${CROSS_PREFIX}/sysroot/usr/${CROSS_PREFIX}/bin/libwinpthread-1.dll ${TOOLCHAIN_ROOT}/${CROSS_PREFIX}/lib/libstdc++-6.dll ${TOOLCHAIN_ROOT}/${CROSS_PREFIX}/lib/libgcc_s_seh-1.dll ${TOOLCHAIN_ROOT}/${CROSS_PREFIX}/lib/libssp-0.dll ${TOOLCHAIN_ROOT}/${CROSS_PREFIX}/lib/libatomic-1.dll" \
    HOST_CONFIGURE_ARGS="--host=${CROSS_PREFIX}" CROSS_HOST=Windows

ADD build-dep-libs.sh /root
RUN SKIP_BUILD_LIBCXX=1 ./build-dep-libs.sh
ENV HOST_RUNTIME_LIBS="$HOST_RUNTIME_LIBS ${BUILD_DEPS_ROOT}/bin/libxml2.dll"
